### PR TITLE
Lili edits jan2021

### PR DESCRIPTION
**Pull request by LilyAndres**
Address some points discussed in the slack platform: 
1) Adding definitions for the CDNO NCF terms (e.g. dietary nutritional component, dietary fibre etc)
2) Fixing non-standard characters (which aren’t compiling in protege) in the template google sheet, e.g.: γ-linolenic acid where the γ doesn’t work. Maybe we can change to gamma-.
3) Checking label extensions e.g. flavonoid c6--c3--c6 in chebi it’s just flavonoids do we want the extra c6-- stuff?Once steps 2-3 are done we can (very easily) make the whole set of concentration terms. Then begin mapping the concentration terms  to INFOODS USDA etc (i’ve made another tab in the spreadsheet for mappings). 
5) Find appropriate parents for the dangling terms that should be under dietary nutritional component (e.g. glycerol, vitamin K etc).

### CODE REVIEW

**Review by kaiiam — CHANGES_REQUESTED** [review]
See comments in slack about how to review this sorry I should have put those comments here so they'd be logged in an open platform. Quick recap again here to maintain provenance:

**mapping.csv:**
 use | delimited feature of robot template for multiple column entries see https://github.com/EnvironmentOntology/envo/wiki/ENVO-Robot-template-and-merge-workflow#columns-with-multiple-entries for an example. 

**sugar derivatives:**

you’ve deleted and re-written everything lines 1-59 are red aka deleted and 1-53 green as in written. This isn’t your fault persay sorry if I didn’t warn you about this but this is probably a unix vs windows thing. Unfortunately the line endings are different on windows vs linx/mac so it makes for the re-writting behaving which makes reviewing pull requests difficult. Would it be possible for you to do it on your linux partition and save it there? or on windows use notepad++ or something like that to format the line endings as unix? I must have removed it and you’d just copied what in the doc makes sense, so you can just download and resave it to that branch on your linux partition.

**Chemica_concentration** Looks good :)

**nutritional_comp_framework** same issue as sugar derivatives everyting is deleted and re-written doing it again in linux should fix it. 

You can do it @LilyAndres you're super close!

**Comment by LilyAndres** [comment]
Thanks @kaiiam, I think the problem was that I was opening the csv files before saving them in Libreoffice in linux. Now I just saved them directly, I changed "," for "|" thanks. 
I think sugar derivatives might be a tricky one, I don't know how the original files had purls at the end? I don't get that when I download and save the file, I run all the steps from https://github.com/Southern-Cross-Plant-Science/cdno/wiki/Intermediate-CDNO-Compile-Instructions but I don't know how they have those purls at the end of the line.

**Review by kaiiam — APPROVED** [review]

**Comment by kaiiam** [comment]
Thanks @LilyAndres, looking at the **sugar derivatives** and **ncf** sheets everything is still deleted and re-written. I'm not sure if it's because of linux/unix vs windows, or it's because there are so many changes to the csvs that it's interpreting them as replacements. 🤷‍♂️ 

You can see the problem I'm describing in the following image of the github differences for the sugar derivatives in this PR. Green is addition/kept lines red is deleted. Deleting and re-writing everything like this makes it really hard to review. 
image

Since this is really the first real release I say we can just go for it for now, but in the future we should move away from hosting the master copy in google docs (their not as stable solution long term as github is). At which time we should be more careful with this i.e. if we only add a few term or changes in a pull request making sure it's not deleting and re-writing the whole file like it's doing now for sugars and ncf. 

> I think sugar derivatives might be a tricky one, I don't know how the original files had purls at the end? 

Don't worry about the last column of urls (not purls, purls are permanent urls), this was my doing. I had added that extra column in the csv but then later removed it in the google docs (as we didn't end up needing it) but I didn't add the change from the google doc to the github version. For now we're treating the google doc as the source of truth, but once we have the release done or sometime in the future we should switch to having the github csv files be the source of truth. I had originally said that I think we'd keep the google doc as the source of truth but after conversations with various colleagues I'm now convinced we should have the edit versions be the github csvs at least in the long term. For now we can keep the google doc for the first release/your thesis. 

We can go ahead and merge this.

**Comment by LilyAndres** [comment]
Thanks @kaiiam, I think that was me just copying and pasting what I had in the google docs. Sorry, from now on I will just make small changes and not copying and pasting everything from google docs. I like google docs but I can adapt to the don't use it for the next step.

**Comment by kaiiam** [comment]
Like I said we can use the google docs for now as you did, but once we've got the first version done, (or some time in the future) we should treat the github csvs as the working copy. The google docs are really convenient I agree and we should use it now while were making lots of changes, but once it's done moving away is better long term (several years down the line etc). Lots of stories about lousing access to your google docs after graduating etc. It's just not a good long term plan.

**Comment by LilyAndres** [comment]
True! Ok, we will do that, thanks.

**Pull request merged**
