### PR TITLE
Issue 32

### PR DESCRIPTION
**Pull request by LilyAndres**
Thanks @kaiiam, here I address issue #32 I added the "INFOODs:" and "USDA_NDB" to the mappings.csv file. Everything should be ok.

### CODE REVIEW

**Comment by kaiiam** [comment]
Hey @LilyAndres it's close but there is still a little issue you'll need to fix. 

For example you have `CDNO:0200015,rhamnose,INFOODs: RHAS|RHAFB`
Remember that the | will treat each thing separately so this will produce:

dbxref1: `INFOODs: RHAS` and dbxref2 `RHAFB`, if you want the infoods/usda tags to show up for everything you'll have to add it to all | seperated lines. Sorry it's a bit inconvenient.

**Review by kaiiam — CHANGES_REQUESTED** [review]
See my comment in the main discussion about the | separated terms. Once you fix that this should be good to merge! Good work @LilyAndres

**Comment by LilyAndres** [comment]
@kaiiam sorry I didn't see that, I made the changes in a new pull request #33. I hope it's ok if not let me know, thanks a lot.

**Comment by kaiiam** [comment]
@LilyAndres I would have just done it here instead of a new PR but that's cool I guess the plan is to just close this one after I merge the other?

**Comment by kaiiam** [comment]
I'll just go ahead and close this.

**Pull request closed without merging**
